import localFont from "next/font/local"
import "./globals.css"
import { AudioProvider } from "@/components/AudioPlayer"

const haasBold = localFont({
  src: "./fonts/AlteHaasBold.ttf",
  variable: "--font-haas-bold",
  weight: "100 900",
})
const hassRegular = localFont({
  src: "./fonts/AlteHaasRegular.ttf",
  variable: "--font-haas-regular",
  weight: "100 900",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${haasBold.variable} ${hassRegular.variable} antialiased max-w-screen-2xl mx-auto`}>
        <AudioProvider>{children}</AudioProvider>
      </body>
    </html>
  )
}
