export const projects = [
  {
    slug: "trackyard",
    name: "Trackyard",
    role: "CTO & Founding Engineer",
    url: "https://trackyard.com",
    tagline: "AI-powered music licensing platform for film and television.",
    description:
      "Trackyard is a music licensing platform built for film and TV professionals. As CTO and founding engineer, I architected the core AI search infrastructure, automated media pipelines, and social content tools that became the company's primary revenue driver.",
    bullets: [
      "Architected and launched an AI-powered music search platform indexing tens of thousands of tracks, becoming the company's core product and primary revenue driver.",
      "Built automated media pipelines that cut catalog processing time by 300%, scaling content operations without adding headcount.",
      "Shipped an AI-driven short-form video generation tool that grew social media engagement 150% within 30 days of launch.",
    ],
    tech: ["Go", "PostgreSQL", "React", "AWS", "AI/ML"],
    github: null,
    featured: true,
  },
  {
    slug: "gallery",
    name: "Gallery",
    role: "Backend Software Engineer II",
    url: "https://gallery.so",
    tagline: "Social platform for sharing and discovering art.",
    description:
      "Gallery is a social platform for sharing art. I built and maintained the backend infrastructure handling millions of media assets, real-time notifications, and third-party data sync.",
    bullets: [
      "Built an ffmpeg-based media processing pipeline handling 3M+ images and videos with concurrency controls and multiple redundancy layers.",
      "Implemented real-time push and web notifications across the application.",
      "Designed and shipped the GraphQL API and cloud architecture on Google Cloud Run and Cloud SQL.",
      "Built an incremental user syncing pattern for third-party data ingestion without disrupting live user sessions.",
    ],
    tech: ["Go", "GraphQL", "PostgreSQL", "Redis", "GCP", "Docker"],
    github: "https://github.com/gallery-so/go-gallery",
    featured: true,
  },
  {
    slug: "gig-app",
    name: "Gig App",
    role: "Founder & Engineer",
    url: "https://gig.app",
    tagline: "Full-stack platform for gigging musicians.",
    description:
      "Gig App is an all-in-one platform for musicians to manage their career. I built the full stack from the React Native mobile app to the Go backend, with a focus on payments infrastructure, caching, and automation.",
    bullets: [
      "Built an automated payout pipeline using Stripe, handling gig payment splits across band members.",
      "Implemented Redis-backed caching for feeds and recommendations, reducing query load at scale.",
      "Shipped AI-powered marketing automation to generate social content and notify followers of upcoming performances.",
      "Deployed full-stack product on Hetzner using Docker: React Native mobile, Next.js web, Go API, PostgreSQL.",
    ],
    tech: ["Go", "React Native", "Next.js", "PostgreSQL", "Redis", "Stripe", "Docker"],
    github: null,
    featured: true,
  },
  {
    slug: "minecraft-plugins",
    name: "Minecraft Plugins",
    role: "Programmer",
    url: null,
    tagline: "Plugins used by thousands of multiplayer servers globally.",
    description:
      "Developed multiple Minecraft plugins used by thousands of public and private multiplayer servers. These range from a full land-claiming and politics system to a package manager for the plugin ecosystem.",
    bullets: [
      "Civilizations: a multiplayer land claiming and politics system where players build cities, declare war, and manage real economic impact.",
      "Bundle: a package manager for Minecraft plugins, providing a central repository and easy install/update workflow.",
      "TownyMenu: a visual admin interface for the Towny plugin, replacing typed commands with a GUI.",
      "Trader: a safe peer-to-peer item trading system between players.",
    ],
    tech: ["Java", "Kotlin"],
    github: "https://github.com/benny-conn/Civilizations",
    featured: true,
  },
  {
    slug: "curation-events",
    name: "Curation Events",
    role: "Co-Founder & Creative Director",
    url: "https://curation.events",
    tagline: "Full-service experiential event studio.",
    description:
      "Co-founded and led a full-service experiential event studio delivering large-scale corporate activations for brands including Spotify and Aetna.",
    bullets: [
      "1,000+ attendees served across New York and Los Angeles.",
      "200+ staff and vendors coordinated across multi-day productions.",
      "Designed custom digital engagement systems: QR-based interactions, real-time leaderboards, live participation tools.",
    ],
    tech: [],
    github: null,
    featured: false,
  },
]
